import { Contract } from "../types";

export const EMPTY: Contract = {
  contractId: "", companyId: "MESA-IT-001", contractCode: "", description: "",
  lessorId: "", leaseCurrency: "EUR", commencementDate: "", endDate: "", status: "DRAFT",
  leaseCategory: "", assetDescription: "", ownershipTransferLikely: false,
  usefulLifeMonths: "", purchaseOption: false, terminationOption: false, renewalOption: false,
  purchaseOptionPrice: "", purchaseOptionDate: "", purchaseOptionReasonablyCertain: false,
  terminationOptionDate: "", terminationOptionPenalty: "", terminationOptionReasonablyCertain: false,
  renewalOptionMonths: "", renewalOptionReasonablyCertain: false,
  exemptShortTerm: false, exemptLowValue: false, separateNonLeaseComponents: false, postingFrequency: "MONTHLY",
  discountRateAnnual: "", dayCountBasis: "ACT/365", paymentTiming: "ARREARS",
  basePaymentAmount: "", initialDirectCosts: "", prepaidAmount: "", leaseIncentives: "",
  restorationProvision: "", discountRateSource: "IBR",
  companyLocalCurrency: "EUR", fxTranslationMethod: "AVERAGE", fxRate: "1", fxRates: null,
  accROU: "02.01", accLeaseLiability: "22.01", accInterestExp: "82.01", accDepExp: "63.01",
  accServiceExp: "64.01", accImpairmentLoss: "65.01", accImpairmentReversal: "75.01",
  accIFRS16Clearing: "50.01", accFxDiff: "86.01", accLeaseExpense: "64.02",
  accIncentiveLiability: "33.01", accRestorationProvision: "34.01",
  splitCurrentNonCurrent: false, accLeaseLiabilityCurrent: "22.01.C", accLeaseLiabilityNonCurrent: "22.01.NC",
  costCenterId: "", businessUnit: "", projectCode: "",
  approvedBy: "", approvedAt: "", submittedBy: "", submittedAt: "",
  createdBy: "admin@mesa.it", createdAt: "", updatedBy: "", updatedAt: "", notes: "",
  modifications: [],
};

export const DEMO_CONTRACTS: Contract[] = [
  {
    ...EMPTY, contractId: "LEA-2024-001", contractCode: "LEA-2024-001",
    description: "Uffici Milano - Via Dante 12", leaseCategory: "PROPERTY",
    assetDescription: "Uffici direzionali piano 3° - 450 mq", lessorId: "L001",
    leaseCurrency: "EUR", commencementDate: "2024-01-01", endDate: "2028-12-31", status: "ACTIVE",
    usefulLifeMonths: "120", renewalOption: true, renewalOptionMonths: "24",
    discountRateAnnual: "3.5", paymentTiming: "ARREARS", basePaymentAmount: "5000",
    initialDirectCosts: "2000", restorationProvision: "1500", discountRateSource: "IBR",
    costCenterId: "CC-ADM", businessUnit: "HQ", postingFrequency: "MONTHLY",
    accROU: "02.01 ROU-Immobili", accLeaseLiability: "22.01 LL-Immobili",
    accInterestExp: "82.01 Int.Leasing", accDepExp: "63.01 Amm.ROU",
    fxRate: "1", createdAt: "2024-01-01T00:00:00Z", modifications: [],
  },
  {
    ...EMPTY, contractId: "LEA-2024-002", contractCode: "LEA-2024-002",
    description: "Flotta Auto - 3 Veicoli", leaseCategory: "VEHICLE",
    assetDescription: "3x Audi A4 Business", lessorId: "L002",
    leaseCurrency: "EUR", commencementDate: "2024-03-01", endDate: "2027-02-28", status: "ACTIVE",
    usefulLifeMonths: "60", purchaseOption: true, purchaseOptionPrice: "15000",
    purchaseOptionDate: "2027-02-28", terminationOption: true, terminationOptionPenalty: "3000",
    terminationOptionDate: "2026-03-01", discountRateAnnual: "4.2", paymentTiming: "ADVANCE",
    basePaymentAmount: "2400", initialDirectCosts: "500", prepaidAmount: "2400",
    leaseIncentives: "200", discountRateSource: "IBR", costCenterId: "CC-OPS",
    businessUnit: "NORTH", postingFrequency: "MONTHLY",
    accROU: "02.02 ROU-Veicoli", accLeaseLiability: "22.02 LL-Veicoli",
    accInterestExp: "82.01 Int.Leasing", accDepExp: "63.02 Amm.ROU",
    splitCurrentNonCurrent: true, fxRate: "1", createdAt: "2024-03-01T00:00:00Z", modifications: [],
  },
  {
    ...EMPTY, contractId: "LEA-2024-003", contractCode: "LEA-2024-003",
    description: "Server Farm - IT Equipment", leaseCategory: "IT_EQUIPMENT",
    assetDescription: "Server rack Dell + storage array", lessorId: "L003",
    leaseCurrency: "EUR", commencementDate: "2024-06-01", endDate: "2028-05-31", status: "ACTIVE",
    usefulLifeMonths: "72", discountRateAnnual: "5.0", paymentTiming: "ARREARS",
    basePaymentAmount: "1800", initialDirectCosts: "300", restorationProvision: "500",
    discountRateSource: "IBR", costCenterId: "CC-IT", businessUnit: "HQ",
    postingFrequency: "QUARTERLY",
    accROU: "02.03 ROU-IT", accLeaseLiability: "22.03 LL-IT",
    accInterestExp: "82.01 Int.Leasing", accDepExp: "63.03 Amm.ROU",
    fxRate: "1", createdAt: "2024-06-01T00:00:00Z", modifications: [],
  },
];
